.\"-
.\" Manual page written by Timothy Brown <tbrown@freeshell.org>
.\"
.\" Copyright (C) 2014 Timothy Brown
.\"
.\" Permission is granted to make and distribute verbatim copies of
.\" this manual provided the copyright notice and this permission notice
.\" are preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Permission is granted to copy and distribute translations of this
.\" manual into another language, under the above conditions for modified
.\" versions, except that this permission notice may be included in
.\" translations approved by the Free Software Foundation instead of in
.\" the original English.
.\"
.\" $Id$
.\"
.Dd November 5, 2024
.Dt MCDS 1
.Os
.Sh NAME
.Nm mcds
.Nd mutt CardDAV query
.Sh SYNOPSIS
.Nm
.Op Fl c Ar config_file
.Op Fl hVvp
.Op Fl q Cm a | e | n | t
.Op Fl S
.Op Fl s Cm a | e | n | t
.Op Fl u Ar URL
.Ar term
.Sh DESCRIPTION
The
.Nm
utility queries a CardDAV server for requested information.
It's primary function is to provide an address query command for
.Xr mutt 1 .
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c Pa config_file
Specifies an alternative configuration file. The default file is
.Pa ~/.mcdsrc .
.It Fl h
Print help text to standard output and exit.
.It Fl p
Force the presentation of a password prompt.
.It Fl q Cm a | e | n | t
The term to query against.
Known terms are:
.Bl -tag -width Ds
.It Cm a
Query for the address field.
.It Cm e
Query for the email field.
This is the default.
.It Cm n
Query for the full-name field.
.It Cm t
Query for the telephone field.
.El
.It Fl S
Save the password.
.It Fl s Cm a | e | n | t
The search term to return.
Known terms are:
.Bl -tag -width Ds
.It Cm a
Query for the address field.
.It Cm e
Query for the email field.
This is the default.
.It Cm n
Query for the full-name field.
.It Cm t
Query for the telephone field.
.El
.It Fl u Ar URL
The URL of the CardDAV server.
.It Fl V
Print the version number and license information of
.Nm
to standard output and exit.
.It Fl v
Enable verbose mode.
Forces
.Nm
to print debugging messages about its progress.
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa ~/.mcdsrc
Configuration file.
Used to set default values for
.Nm ,
but can be overridden with command-line arguments.
Formatted as a list of
.Dq Cm key No \&= Ar value
pairs separated by newlines.
.Pp
The keys are as follows:
.Bl -tag -width Ds
.It Cm url No \&= Ar URL
The URL of the CardDAV server.
.It Cm verify No \&= Op Cm yes | no
Verify server certificate if connecting over HTTPS.
Disabled by default.
.It Cm netrc No \&= Op Cm yes | no
Enable reading the
.Pa ~/.netrc
file.
Disabled by default.
.It Cm username No \&= Ar USERNAME
The username to login to the CardDAV server with.
If a username is specified
.Nm
will not use the
.Pa ~/.netrc
file.
.It Cm password_file No \&= Ar password.gpg
The GPG encrypted file containing the password for the CardDAV server.
.It Cm libsecret No \&= Op Cm yes | no
Use 
.Lb libsecret
to store and retrieve the password.
.El
.It Pa ~/.netrc
Used to access your username and password when authenticating with the
CardDAV server, if you have not specified your username and password
file in
.Pa ~/.mcdsrc .
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Query a CardDAV server for email addresses corresponding to
.Dq Ben :
.Bd -literal -offset indent
$ mcds -u https://localhost/caldav.php/username/addressbook/ Ben
ben@example.net        Ben Smith
\&...
.Ed
.Pp
To use
.Nm
with
.Nm mutt ,
add the following to your
.Xr muttrc 5 :
.Bd -literal -offset indent
set query_command="mcds -u https://localhost/caldav.php/username/addressbook/ '%s'"
.Ed
.Pp
This query can be simplified by putting the relevant values in
.Pa ~/.mcdsrc :
.Bd -literal -offset indent
url = https://localhost/caldav.php/username/addressbook/
verify = no
netrc = yes
.Ed
.Pp
Now the query command can be shortened to:
.Bd -literal -offset indent
set query_command="mcds '%s'"
.Ed
.Pp
When compiled against libsecret,
.Nm
saves passwords provided at the password prompt. To replace the saved
password (or to clear, entering no password at the prompt):
.Bd -literal -offset indent
mcds -p
.Ed
.Sh SEE ALSO
.Xr curl 1 ,
.Xr gpg2 1 ,
.Xr mutt 1 ,
.Xr muttrc 5 ,
.Xr netrc 5
.Sh AUTHORS
The
.Nm
utility is maintained by
.An Timothy Brown Aq Mt tbrown@freeshell.org
